### ISSUE TITLE
执行 flutter run 直接报错，无法运行

### ISSUE THREAD

**Issue by hlj2722** [ZDfordream/FlutterTianYue#1]
版本
D:\flutter_app\Flutter-TianYue>flutter --version
Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (10 days ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

D:\flutter_app\Flutter-TianYue>dart --version
Dart VM version: 2.3.0 (Fri May 3 10:32:31 2019 +0200) on "windows_x64"

---------------------------------------------------------------------------------------------------
D:\flutter_app\Flutter-TianYue>flutter run
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                              1.3s
Resolving dependencies...                                          21.6s

Compiler message:
lib/app/guide_scene.dart:108:13: Error: No named parameter with the name 'cacheExtent'.
            cacheExtent: 100,
            ^^^^^^^^^^^
file:///D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/flukit-1.0.0/lib/src/swiper.dart:185:3: Context: Found this candidate, but the arguments don't match.
  Swiper({
  ^
lib/book_home/home_banner.dart:37:9: Error: No named parameter with the name 'cacheExtent'.
        cacheExtent: 100,
        ^^^^^^^^^^^
file:///D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/carousel_slider-1.3.0/lib/carousel_slider.dart:9:3: Context: Found this candidate, but the arguments don't match.
  CarouselSlider({
  ^
Compiler failed on D:\flutter_app\Flutter-TianYue\lib/main.dart
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        18.8s
Gradle task assembleDebug failed with exit code 1

**Comment by ZDfordream** [comment]
我本地修改了pageview的源码导致，已经改回去了，你再拉去试试，done～

**Comment by hlj2722** [comment]
之前的问题已经不在出现了，但是又出现了下面的问题
Compiler message:
lib/comic_detail/comic_detail_tab_three.dart:85:11: Error: Superclass has no method named 'build'.
    super.build(context);
          ^^^^^
Compiler failed on D:\flutter_app\Flutter-TianYue\lib\main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1
-----------------------------------------------------------------------
请问你的 flutter 和 dart 都是什么版本的

**Comment by ZDfordream** [comment]
flutter 1.0.0,dart 2.1.0; 已调整，之前的plugin有兼容问题，你重新拉去，非常感谢你的支持～
