### ISSUE TITLE
好想有点卡😂

### ISSUE THREAD

**Issue by hangaoke1** [ZDfordream/FlutterTianYue#5]
大佬，你的这个demo跑起来后好想挺卡顿的，有研究过是什么原因吗？

**Comment by ZDfordream** [comment]
打release包会稍微好一点，然后低端机是稍微有点卡。比如pageview显示图片需要优化，不然没有预加载，显示慢，但我改源码后，由于你们本地的sdk没有改，会导致项目运行不起来；可以多研究研究，欢迎交流

**Comment by hangaoke1** [comment]
哈哈，好的，感谢
